Repository softeerbootcamp-3rd/be-was, pull requests merged in 2024-02, with the labels that each got.

#244 [jjyk999] Step-3 다양한 컨텐츠 지원
  readme.md
  src/main/java/webserver/RequestHandler.java
Labels: step-3

#227 [binaryrain97] step-6 동적인 HTML
  README.md
  src/main/java/controller/FirstController.java
  src/main/java/controller/LastController.java
  src/main/java/controller/MainController.java
  src/main/java/controller/UserController.java
  src/main/java/db/SessionStorage.java
  src/main/java/model/Request.java
  src/main/java/model/Response.java
  src/main/java/model/Session.java
  src/main/java/model/StatusCode.java
  src/main/java/utils/Util.java
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
Labels: step-6

#223 [zensen6] Step-6 동적인 HTML
  src/main/java/Controller/User/QnaController.java
  src/main/java/Controller/User/QnaLogic/QnaLogic.java
  src/main/java/Controller/User/UserController.java
  src/main/java/Controller/User/UserLogic/UserLogic.java
  src/main/java/Functions/FileBytes.java
  src/main/java/Functions/UserListFunction.java
  src/main/java/HTTPModel/HttpStatus.java
  src/main/java/HTTPModel/Request.java
  src/main/java/HTTPModel/Response.java
  src/main/java/HTTPModel/Session.java
  src/main/java/HandlerMapping/HandlerMapping.java
  src/main/java/SessionManager/SessionManager.java
  src/main/java/db/Database.java
  src/main/java/db/QnaDatabase.java
  src/main/java/model/Qna.java
  src/main/java/model/User.java
  src/main/java/webserver/HTTPHandler/RequestMake.java
  src/main/java/webserver/HTTPHandler/ResponseMake.java
  src/main/java/webserver/RequestHandler.java
  src/main/resources/static/css/styles.css
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/signup_failed.html
  src/test/java/ControllerTest.java
  src/test/java/UserLogicTest.java
Labels: step-6

#231 [ossu] step-6 동적인 HTML
  src/main/java/controller/UserController.java
  src/main/java/http/request/HttpRequest.java
  src/main/java/http/response/HttpResponse.java
  src/main/java/service/UserService.java
  src/main/java/utils/Parser.java
  src/main/java/utils/ValidatorController.java
  src/main/java/utils/ValidatorControllerMapper.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/ResourceHandler.java
  src/main/java/webserver/WebServer.java
  src/main/resources/templates/404.html
  src/main/resources/templates/user/list.html
Labels: step-6

#235 [yeriinnn] Step-5 쿠키를 이용한 로그인
  .github/workflows/merge.yml
  src/main/java/annotation/PostMapping.java
  src/main/java/controller/Controller.java
  src/main/java/db/Database.java
  src/main/java/db/SessionManager.java
  src/main/java/exception/NotSupportedContentTypeException.java
  src/main/java/http/Body.java
  src/main/java/http/Cookie.java
  src/main/java/http/Header.java
  src/main/java/http/HttpHeader.java
  src/main/java/http/HttpRequest.java
  src/main/java/http/HttpResponse.java
  src/main/java/http/HttpStatus.java
  src/main/java/http/Session.java
  src/main/java/model/User.java
  src/main/java/model/UserFactory.java
  src/main/java/utils/StringUtils.java
  src/main/java/view/MainPageView.java
  src/main/java/webserver/ContentType.java
  src/main/java/webserver/DispatcherServlet.java
  src/main/java/webserver/HandlerMapping.java
  src/main/java/webserver/RequestHandler.java
  src/main/resources/templates/error.html
  src/main/resources/templates/user/form.html
Labels: step-5

#233 [Yoon-Suji] step-6 동적인 HTML
  docs/JavaThread.md
  src/main/java/constant/HttpHeader.java
  src/main/java/controller/Controller.java
  src/main/java/controller/DefaultController.java
  src/main/java/controller/UserController.java
  src/main/java/db/SessionDatabase.java
  src/main/java/db/UserDatabase.java
  src/main/java/dto/HttpHeaders.java
  src/main/java/dto/HttpRequestDto.java
  src/main/java/dto/HttpRequestDtoBuilder.java
  src/main/java/dto/HttpResponseDto.java
  src/main/java/dto/HttpResponseDtoBuilder.java
  src/main/java/model/Session.java
  src/main/java/service/UserService.java
  src/main/java/util/ControllerMapper.java
  src/main/java/util/HtmlBuilder.java
  src/main/java/util/HttpResponseUtil.java
  src/main/java/util/SessionUtil.java
  src/main/java/util/WebUtil.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/WebServer.java
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
  src/test/java/controller/UserControllerTest.java
  src/test/java/db/SessionDatabaseTest.java
  src/test/java/service/UserServiceTest.java
  src/test/java/util/ControllerMapperTest.java
  src/test/java/util/SessionUtilTest.java
  src/test/java/util/WebUtilTest.java
  src/test/java/webserver/RequestHandlerTest.java
Labels: step-6

#237 [dlwnsgus07] Step 6 동적인 HTML + 피드백 반영
  src/main/java/annotation/Controller.java
  src/main/java/annotation/GetMapping.java
  src/main/java/annotation/PostMapping.java
  src/main/java/annotation/RequestMapping.java
  src/main/java/config/AppConfig.java
  src/main/java/controller/UserController.java
  src/main/java/controller/UserControllerImpl.java
  src/main/java/exception/InternalServerError.java
  src/main/java/exception/InternalServerException.java
  src/main/java/exception/InvalidLogin.java
  src/main/java/factory/HttpRequestFactoryImpl.java
  src/main/java/filter/AuthFilter.java
  src/main/java/filter/Filter.java
  src/main/java/handler/DynamicResponseHandlerImpl.java
  src/main/java/handler/StaticResponseHandlerImpl.java
  src/main/java/model/http/OptionHeaders.java
  src/main/java/model/http/request/RequestHeaders.java
  src/main/java/service/HttpResponseSendServiceImpl.java
  src/main/java/service/UserService.java
  src/main/java/service/UserServiceImpl.java
  src/main/java/session/Session.java
  src/main/java/util/FileDetector.java
  src/main/java/util/HtmlParser.java
  src/main/java/util/UrlControllerMapper.java
  src/main/java/webserver/RequestHandler.java
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
  src/test/java/webApplicationServer/controller/FakeUserService.java
  src/test/java/webApplicationServer/controller/UserControllerImplTest.java
Labels: step-6

#239 [jiaeYoon] step-5 쿠키를 이용한 로그인
  README.md
  src/main/java/common/Binder.java
  src/main/java/common/InputValidator.java
  src/main/java/common/Logger.java
  src/main/java/common/WebServerConfig.java
  src/main/java/common/config/WebServerConfig.java
  src/main/java/common/exception/EmptyFormException.java
  src/main/java/common/util/FileManager.java
  src/main/java/common/util/Util.java
  src/main/java/common/validate/InputValidate.java
  src/main/java/common/view/OutputView.java
  src/main/java/controller/UserController.java
  src/main/java/dto/HttpRequest.java
  src/main/java/dto/HttpResponse.java
  src/main/java/dto/LoginRequest.java
  src/main/java/dto/RequestLineDto.java
  src/main/java/http/ExceptionHandler.java
  src/main/java/http/MethodMapper.java
  src/main/java/http/RequestParser.java
  src/main/java/http/constants/ContentType.java
  src/main/java/http/constants/Status.java
  src/main/java/service/UserService.java
  src/main/java/session/SessionManager.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/RequestParser.java
  src/main/java/webserver/Response.java
  src/main/java/webserver/ResponseHandler.java
  src/main/resources/templates/not_found.html
  src/main/resources/templates/user/form_fail.html
  src/main/resources/templates/user/form_userId_duplicate_fail.html
  src/test/java/common/BinderTest.java
  src/test/java/common/InputValidatorTest.java
  src/test/java/common/util/FileManagerTest.java
  src/test/java/common/util/UtilTest.java
  src/test/java/http/ContentTypeTest.java
  src/test/java/http/MethodMapperTest.java
  src/test/java/http/RequestParserTest.java
  src/test/java/service/UserServiceTest.java
  src/test/java/util/UtilTest.java
  src/test/java/webserver/ResponseTest.java
Labels: step-5

#241 [Hymin2] step-5 쿠키를 이용한 로그인
  src/main/java/controller/UserController.java
  src/main/java/db/Database.java
  src/main/java/dto/UserRequest.java
  src/main/java/service/UserService.java
  src/main/java/webserver/WebServer.java
  src/main/java/webserver/adapter/MethodRequestAdapter.java
  src/main/java/webserver/exception/LoginFailedException.java
  src/main/java/webserver/handler/ExceptionHandler.java
  src/main/java/webserver/parser/RequestParser.java
  src/main/java/webserver/response/Response.java
  src/main/java/webserver/session/Session.java
  src/main/java/webserver/session/SessionDatabase.java
  src/main/java/webserver/session/SessionManager.java
  src/main/java/webserver/session/SessionScheduler.java
  src/main/java/webserver/status/ErrorCode.java
  src/test/java/webserver/adapter/ResourceAdapterTest.java
  src/test/java/webserver/session/SessionDatabaseTest.java
Labels: step-5

#243 [timido7021] step-6 동적인 HTML
  src/main/java/controller/StaticResourceController.java
  src/main/java/controller/UserController.java
  src/main/java/controller/util/FileUtil.java
  src/main/java/webserver/WebServer.java
  src/main/java/webserver/http/SessionManager.java
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/form_failed.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
  src/test/java/controller/StaticResourceControllerTest.java
  src/test/java/controller/UserControllerTest.java
  src/test/java/controller/util/DateTimeUtilTest.java
  src/test/java/controller/util/FileUtilTest.java
  src/test/java/service/UserServiceTest.java
  src/test/java/utils/FileUtilTest.java
  src/test/java/webserver/http/HttpRequestTest.java
Labels: step-6

#247 [yo0919] step-6 동적인 HTML
  README.md
  src/main/java/controller/UserController.java
  src/main/java/db/Database.java
  src/main/java/http/mapping/ControllerMethodMapper.java
  src/main/java/http/request/HttpRequest.java
  src/main/java/http/request/HttpRequestParser.java
  src/main/java/http/request/parser/HttpRequestParser.java
  src/main/java/http/request/parser/RequestCookieParser.java
  src/main/java/http/response/HttpResponse.java
  src/main/java/http/response/handler/LoginResponseHandler.java
  src/main/java/http/response/renderer/HtmlResponseRenderer.java
  src/main/java/http/session/SessionHandler.java
  src/main/java/http/session/SessionStorage.java
  src/main/java/model/User.java
  src/main/java/service/UserService.java
  src/main/java/utils/FileUtils.java
  src/main/java/utils/StaticFileUtils.java
  src/main/java/utils/UserHtmlConverter.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/WebServer.java
  src/main/resources/static/css/styles.css
  src/main/resources/templates/index.html
  src/main/resources/templates/user/list.html
  src/test/java/http/request/HttpRequestParserTest.java
  src/test/java/http/session/SessionStorageTest.java
Labels: step-6

#253 [thecloer] step-6 동적인 HTML
  README.md
  build.gradle
  docs/images/was-architecture.png
  docs/was-architecture.png
  src/main/java/controller/ResourceController.java
  src/main/java/controller/UserController.java
  src/main/java/exception/HttpBaseException.java
  src/main/java/exception/RedirectException.java
  src/main/java/pipeline/RequestPipeline.java
  src/main/java/pipeline/Router.java
  src/main/java/pipeline/requestProcessor/AuthFilter.java
  src/main/java/pipeline/requestProcessor/RequestProcessor.java
  src/main/java/pipeline/responseProcessor/CommonComponentInjector.java
  src/main/java/pipeline/responseProcessor/ResponseProcessor.java
  src/main/java/pipeline/responseProcessor/SessionCookieRefresher.java
  src/main/java/pipeline/responseProcessor/templateEngine/TemplateComponents.java
  src/main/java/pipeline/responseProcessor/templateEngine/TemplateRenderer.java
  src/main/java/session/Session.java
  src/main/java/session/SessionManager.java
  src/main/java/util/FileReader.java
  src/main/java/util/RequestParser.java
  src/main/java/util/http/HttpMessage.java
  src/main/java/util/http/HttpMethod.java
  src/main/java/util/http/HttpRequest.java
  src/main/java/util/http/HttpResponse.java
  src/main/java/webserver/ApplicationContainer.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/RequestPipeline.java
  src/main/java/webserver/Router.java
  src/main/java/webserver/WebServer.java
  src/main/resources/templates/404.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/profile.html
  src/test/java/controller/UserControllerTest.java
  src/test/java/model/UserTest.java
  src/test/java/pipeline/responseProcessor/TemplateRendererTest.java
  src/test/java/util/JSONTest.java
  src/test/java/util/ModelConverterTest.java
  src/test/java/util/UriHelperTest.java
Labels: step-6

#257 [Yang-soeun] step-6 동적인 HTML
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/controller/HomeController.java
  src/main/java/controller/UserController.java
  src/main/java/model/HttpRequest.java
  src/main/java/model/HttpResponse.java
  src/main/java/service/HomeService.java
  src/main/java/service/SessionManager.java
  src/main/java/service/UserService.java
  src/main/java/util/URLMapper.java
  src/main/resources/templates/index.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
  src/test/java/service/UserServiceTest.java
Labels: step-6

#263 [taegon98] step-7 게시판 기능 완성
  README.md
  build.gradle
  docs/step-7-README.md
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/controller/BoardController.java
  src/main/java/controller/HomeController.java
  src/main/java/controller/UserController.java
  src/main/java/db/Database.java
  src/main/java/model/Board.java
  src/main/java/model/User.java
  src/main/java/request/http/HttpRequest.java
  src/main/java/request/http/RequestHeaders.java
  src/main/java/response/http/HttpResponse.java
  src/main/java/service/BoardService.java
  src/main/java/service/UserService.java
  src/main/java/util/Parser.java
  src/main/java/webserver/DispatcherServlet.java
  src/main/resources/templates/board/show.html
  src/main/resources/templates/board/write.html
  src/main/resources/templates/index.html
  src/main/resources/templates/user/list.html
  src/test/java/controller/HomeControllerTest.java
  src/test/java/controller/UserControllerTest.java
  src/test/java/service/UserServiceTest.java
  src/test/java/util/AuthFilterTest.java
Labels: step-7

#267 [eekrwl] step-7 웹 서버 7단계 - 게시판 기능 완성
  src/main/java/annotation/RequestMapping.java
  src/main/java/auth/AuthFilter.java
  src/main/java/auth/SessionManager.java
  src/main/java/controller/Controller.java
  src/main/java/controller/ControllerContainer.java
  src/main/java/controller/FrontController.java
  src/main/java/controller/IndexController.java
  src/main/java/controller/PostController.java
  src/main/java/controller/UserController.java
  src/main/java/controller/dto/InputData.java
  src/main/java/controller/dto/ListMapData.java
  src/main/java/controller/dto/OutputData.java
  src/main/java/db/PostRepository.java
  src/main/java/db/UserRepository.java
  src/main/java/exception/CustomException.java
  src/main/java/exception/ErrorCode.java
  src/main/java/http/HttpRequest.java
  src/main/java/http/HttpResponse.java
  src/main/java/http/HttpStatus.java
  src/main/java/http/ResponseHeaderMaker.java
  src/main/java/model/Comment.java
  src/main/java/model/Post.java
  src/main/java/view/View.java
  src/main/java/view/ViewMaker.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/WebServer.java
  src/main/resources/templates/error.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
Labels: step-7

#256 [jbonnie] step 6, 7 게시판 기능 완성
  src/main/java/config/Config.java
  src/main/java/controller/Controller.java
  src/main/java/db/Database.java
  src/main/java/dto/request/FirstClassCollection.java
  src/main/java/dto/request/GetRequestEnum.java
  src/main/java/dto/request/HTTPRequestDto.java
  src/main/java/dto/request/HeaderEnum.java
  src/main/java/dto/request/PostRequestEnum.java
  src/main/java/dto/response/HTTPResponseDto.java
  src/main/java/dto/response/ResponseEnum.java
  src/main/java/model/Post.java
  src/main/java/model/Session.java
  src/main/java/service/GetService.java
  src/main/java/service/PostService.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/WebServer.java
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
  src/test/java/service/GetServiceTest.java
  src/test/java/service/PostServiceTest.java
Labels: step-6, step-7

#258 [Tin9oo] step-6 동적인 HTML & step-7 게시판 기능 완성
  .gitignore
  README.md
  build.gradle
  src/main/java/controller/HttpMethod.java
  src/main/java/controller/RequestDataController.java
  src/main/java/controller/ResourceMapping.java
  src/main/java/controller/Route.java
  src/main/java/data/RequestData.java
  src/main/java/data/Response.java
  src/main/java/db/Database.java
  src/main/java/db/Session.java
  src/main/java/model/Post.java
  src/main/java/service/UserService.java
  src/main/java/util/ByteReader.java
  src/main/java/util/DynamicHtml.java
  src/main/java/util/MethodMapper.java
  src/main/java/util/RequestParserUtil.java
  src/main/java/util/ResourceLoader.java
  src/main/java/util/ResponseBuilder.java
  src/main/java/webserver/RequestHandler.java
  src/main/resources/templates/qna/form.html
  src/test/java/Service/UserServiceTest.java
  src/test/java/controller/RequestDataControllerTest.java
  src/test/java/util/RequestParserUtilTest.java
  src/test/java/util/ResourceLoaderTest.java
  src/test/java/util/ResponseBuilderTest.java
Labels: step-6, step-7

#268 [h-sooah] step-7 게시판 기능 완성
  index.html
  src/main/java/controller/PostController.java
  src/main/java/controller/UserController.java
  src/main/java/dao/FileDao.java
  src/main/java/dao/PostDao.java
  src/main/java/dao/UserDao.java
  src/main/java/dto/PostDto.java
  src/main/java/file/MultipartFile.java
  src/main/java/model/File.java
  src/main/java/model/Post.java
  src/main/java/model/User.java
  src/main/java/type/MimeType.java
  src/main/java/util/ControllerMapper.java
  src/main/java/util/JdbcUtil.java
  src/main/java/util/JsonConverter.java
  src/main/java/util/MultipartParser.java
  src/main/java/util/ResourceManager.java
  src/main/java/util/SessionManager.java
  src/main/java/util/StringParser.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/RequestMappingHandler.java
  src/main/java/webserver/WebServer.java
  src/main/java/webserver/http/HttpHeader.java
  src/main/java/webserver/http/HttpRequest.java
  src/main/java/webserver/http/HttpResponse.java
  src/main/java/webserver/http/HttpStatus.java
  src/main/resources/static/js/logout.js
  src/main/resources/templates/error/400.html
  src/main/resources/templates/error/404.html
  src/main/resources/templates/error/405.html
  src/main/resources/templates/error/500.html
  src/main/resources/templates/index.html
  src/main/resources/templates/post/post_detail.html
  src/main/resources/templates/post/write.html
  src/test/java/UserControllerTest.java
  test.mv.db
  test.trace.db
Labels: step-7

#262 [PKafka0320] step-7 게시판 기능 완성
  .gitignore
  README.md
  build.gradle
  docs/step4.md
  docs/step7.md
  src/main/java/constants/HtmlContent.java
  src/main/java/constants/StatusCode.java
  src/main/java/controller/HomeController.java
  src/main/java/controller/PostController.java
  src/main/java/controller/UserController.java
  src/main/java/db/Database.java
  src/main/java/db/PostDatabase.java
  src/main/java/model/Post.java
  src/main/java/model/Request.java
  src/main/java/service/PostService.java
  src/main/java/service/UserService.java
  src/main/java/utils/HtmlBuilder.java
  src/main/java/utils/ParamBuilder.java
  src/main/java/webserver/RequestHandler.java
  src/main/resources/templates/404.html
  src/main/resources/templates/index.html
  src/main/resources/templates/post/show.html
  src/main/resources/templates/post/write.html
  src/main/resources/templates/post/write_failed.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form_dup.html
  src/main/resources/templates/user/form_failed.html
  src/test/java/db/DatabaseTest.java
  src/test/java/service/UserServiceTest.java
Labels: step-7
